services:
  - type: web
    name: fdtracker
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fdtracker-db
          property: connectionString
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: fdtracker-db
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: fdtracker-db
    databaseName: fdtracker
    user: fduser
    plan: free