services:
  - type: web
    name: fdtracker
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: fdtracker-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fdtracker-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: fdtracker-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: fdtracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fdtracker-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: fdtracker-db
    databaseName: fdtracker
    user: fduser
    plan: free